"use client";

import { motion } from "framer-motion";
import { useState } from "react";

export default function Home() {

  const [active, setActive] = useState(0);
  const [menuOpen, setMenuOpen] = useState(false); // ✅ FIX

  const steps = [
    {
      title: "Discussion",
      desc: "In this step, client requirements are discussed in detail."
    },
    {
      title: "Concepts & Initiatives",
      desc: "Various ideas and concepts are generated by the team."
    },
    {
      title: "Testing & Trying",
      desc: "The developed solution is tested carefully."
    },
    {
      title: "Execute & Install",
      desc: "Final solution is executed and delivered successfully."
    }
  ];

  return (
    <div className="bg-[#020617] text-white">

      {/* Navbar */}
      <nav className="fixed top-0 w-full z-50 backdrop-blur-md bg-black/40 border-b border-gray-800 px-6 py-4">

        <div className="flex justify-between items-center">

          <a href="/" className="text-xl font-bold text-blue-400">
            VareX Tech Solutions
          </a>

          <div className="hidden md:flex gap-6">
            <a href="/" className="hover:text-blue-400">Home</a>
            <a href="/services" className="hover:text-blue-400">Services</a>
            <a href="/contact" className="hover:text-blue-400">Contact</a>
          </div>

          <button
            className="md:hidden text-white text-2xl"
            onClick={() => setMenuOpen(!menuOpen)} // ✅ FIX
          >
            ☰
          </button>

        </div>

        {menuOpen && ( // ✅ FIX
          <div className="md:hidden mt-4 flex flex-col gap-4 text-center bg-[#020617] p-4 rounded-lg">
            <a href="/">Home</a>
            <a href="/services">Services</a>
            <a href="/contact">Contact</a>
          </div>
        )}

      </nav>

      {/* Hero */}
      <section className="relative h-screen flex items-center justify-center text-center overflow-hidden">

        <video autoPlay loop muted playsInline className="absolute w-full h-full object-cover">
          <source src="/hero.mp4" type="video/mp4" />
        </video>

        <div className="absolute inset-0 bg-black/70"></div>

        <div className="relative z-10 px-6">
          <motion.h1
            initial={{ opacity: 0, y: 80 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1 }}
            className="text-4xl md:text-6xl font-bold"
          >
            Building Scalable Digital Platforms for Global Businesses
          </motion.h1>

          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="mt-6 text-gray-300 max-w-2xl mx-auto"
          >
            We help businesses grow with Web, Android, Cloud, and Automation solutions.
          </motion.p>
        </div>

      </section>

      {/* SERVICES */}
      <section className="py-24 px-6 bg-white text-black">

        <h2 className="text-3xl md:text-5xl font-bold text-center mb-16">
          Solutions We Provide
        </h2>

        <div className="max-w-6xl mx-auto grid md:grid-cols-3 gap-10">

          {["Web Development","Android Development","Cloud Solutions","RPA Services","QA & Testing","Custom Software"].map((s,i)=>(
            <motion.div
              key={i}
              whileHover={{ scale: 1.08 }}
              className="bg-gray-100 p-8 rounded-xl shadow hover:shadow-lg"
            >
              <h3 className="text-xl font-semibold text-blue-500 mb-3">{s}</h3>
              <p className="text-gray-600 text-sm">
                High-quality {s.toLowerCase()} solutions for modern businesses.
              </p>
            </motion.div>
          ))}

        </div>

      </section>

      {/* How We Work */}
      <section className="py-24 px-6 bg-white text-black text-center">

        <h2 className="text-3xl md:text-4xl font-bold mb-12">
          How We Work
        </h2>

        <div className="grid md:grid-cols-4 gap-10 max-w-6xl mx-auto">

          {[
            {
              title: "Discussion",
              desc: "We understand your business goals and requirements in detail."
            },
            {
              title: "Planning",
              desc: "We create strategies and concepts tailored for your needs."
            },
            {
              title: "Development",
              desc: "Our team builds and tests the solution carefully."
            },
            {
              title: "Delivery",
              desc: "Final product is deployed and delivered successfully."
            }
          ].map((item, i) => (

            <div key={i} onClick={() => setActive(i)} className="cursor-pointer">

              <motion.div
                animate={{
                  scale: active === i ? 1.2 : 1,
                  backgroundColor: active === i ? "#3b82f6" : "#e5e7eb",
                  color: active === i ? "#fff" : "#000"
                }}
                transition={{ duration: 0.3 }}
                className="w-14 h-14 mx-auto rounded-full flex items-center justify-center mb-4"
              >
                {i + 1}
              </motion.div>

              <h3 className="font-semibold mb-2 text-lg">
                {item.title}
              </h3>

              <motion.p
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: active === i ? 1 : 0.6 }}
                className="text-gray-600 text-sm"
              >
                {item.desc}
              </motion.p>

            </div>

          ))}

        </div>

      </section>

      {/* Footer */}
        <footer className="bg-gradient-to-r from-[#020617] to-[#0f172a] text-white px-10 py-16">

          <div className="grid md:grid-cols-3 gap-10">

            <div>
              <h2 className="text-2xl font-bold text-blue-400 mb-4">
                VareX Tech
              </h2>

              <p className="text-gray-400 mb-6 leading-relaxed">
                VareX Tech Solutions is a trusted technology partner providing Web,
                Android, Cloud, RPA, and QA services.
              </p>

              <p className="text-gray-400">
                📧 contact@varextech.com
              </p>
            </div>

            <div>
              <h3 className="text-xl font-semibold mb-4">Useful Links</h3>
              <ul className="space-y-3 text-gray-400">
                <li><a href="/">Home</a></li>
                <li><a href="/services">Services</a></li>
                <li><a href="/contact">Contact</a></li>
              </ul>
            </div>

            <div>
              <h3 className="text-xl font-semibold mb-4">Our Services</h3>
              <ul className="space-y-3 text-gray-400">
                <li>Web Development</li>
                <li>Android Development</li>
                <li>Cloud Solutions</li>
                <li>RPA Services</li>
                <li>QA & Testing</li>
              </ul>
            </div>

          </div>

          <div className="border-t border-gray-800 mt-10 pt-6 text-center text-gray-500 text-sm">
            © 2026 VareX Tech Solutions. All rights reserved.
          </div>

        </footer>

    </div>
  );
}